[Demo] Dojo - Using Template Mixin
vn-dungnc/demo-dojo-training pull request #5
Opened 2022-03-14 02:38 UTC by vn-dungnc

ref: #### 

------

### Task
- Using Template Mixin
### Impact range
- ....

### Verificaiton point
- Successfully create widget through template mixin.

### Test report

- ...

### Memo
- ....

-------

### Schedule
- Investigate: 10 Mar 2022
- Implement: 14 Mar 2022
- Review: 14 Mar 2022

2022-03-14 08:23 UTC, vn-landt requested changes
@vn-dungnc san,
Thank for your work. Please check & fix the comments.

Thank's so much!

2022-03-14 08:23 UTC, vn-landt commented on AuthorWidget.js
> +],function(declare, _WidgetBase, _OnDijitClickMixin, _TemplatedMixin, template){
`_OnDijitClickMixin ` seems unnecessary to use, can use `data-dojo-attach-event` `onClick` or `dojo/on` to handle it

2022-03-14 08:23 UTC, vn-landt commented on index.html
> +    <button data-dojo-type="dijit/form/Button">My Button</button>
Why is there a button here, but you have to click on the title? If possible, please edit by manipulating the button to update the title.

2022-03-14 08:23 UTC, vn-landt commented on templates/AuthorWidget.html
> +	<div class="${baseClass}Title" data-dojo-attach-point="titleNode" data-dojo-attach-event="ondijitclick:_onClick"></div>
Ditto. Can using `data-dojo-attach-event="onClick:_onClick"` or `dojo/on` to handle it.

2022-03-14 08:23 UTC, vn-landt commented on AuthorWidget.js
> +				this.titleNode.innerHTML = this.title + " was clicked " + (++this._counter) + " times.";
Should declare elements called by `data-dojo-attach-point `. Ex:` this.titleNode` in this case.

2022-03-14 08:37 UTC, vn-huynhnn requested changes

2022-03-14 08:37 UTC, vn-huynhnn commented on AuthorWidget.js
> +		_onClick: function(){
Coding style
```suggestion
		_onClick: function() {
```

2022-03-14 08:37 UTC, vn-huynhnn commented on AuthorWidget.js
> +			if(this._firstClicked){
Coding style 
```suggestion
			if (this._firstClicked) {
```

2022-03-14 08:37 UTC, vn-huynhnn commented on AuthorWidget.js
> +		}
Coding style
```suggestion
		postCreate: function() {
			this.titleNode.innerHTML = this.title;
		}
```

2022-03-15 02:51 UTC, vn-landt approved these changes
@vn-dungnc san,
Thank for your work, the `basic widget` is look OK!

2022-03-15 03:46 UTC, vn-landt requested changes
@vn-dungnc san,
Please check the comment. Thank's so much!

2022-03-15 03:46 UTC, vn-landt commented on templates/AuthorWidget.html
> +    <button class="${baseClass}Button" data-dojo-attach-point="buttonNode"><span>Click</span></button>
`${baseClass}` seems unnecessary. 

About the `titleNode` :
 - can you try to use `data-dojo-type="dijit/_WidgetBase"` & set value in `AuthorWidget`.
 - Ex:
```
  <span class="title" data-dojo-type="dijit/_WidgetBase" data-dojo-props="_setValueAttr:{node:'domNode',type:'innerText'}" data-dojo-attach-point="titleNode"></span>
```

About the `buttonNode`:
 - Can you try to use `dijit.form.Button`. Because using widgets will be used a lot in future work, so get used to it
 - Ex:
 ```
<div class="button" data-dojo-type="dijit.form.Button" data-dojo-attach-point="buttonNode">Click</div>
```

2022-03-15 03:46 UTC, vn-landt commented on AuthorWidget.js
> +        },
Ditto, can try to use `set` value `title` in `_onClick` fuction.
- ex:
```
this.titleNode.set('value',....
```

2022-03-15 03:46 UTC, vn-landt commented on index.html
> +            data-dojo-config="isDebug: 1, async: 1, parseOnLoad: 1"></script>
Use in `dojoConfig ` variable.

2022-03-15 03:46 UTC, vn-landt commented on templates/css/style.css
> +        }
The style css `body` structure will usually precede other style elements, please check again!

2022-03-23 02:13 UTC, vn-landt requested changes
@vn-dungnc san,
The basic look OK. Check comment & fix it.
Please note and learn about coding style for future tasks.

2022-03-23 02:13 UTC, vn-landt commented on templates/css/style.css
> +/*# sourceMappingURL=style.css.map */
add new line at EOF.

2022-03-23 02:33 UTC, vn-landt approved these changes
@vn-dungnc san,
Thank for your work. It's look OK!

2022-03-23 02:33 UTC, merged